version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx configuration
      - ./certs:/etc/letsencrypt:ro            # SSL certificates
      - ./nginx-logs:/var/log/nginx            # Log directory
    networks:
      - shared_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      nginx:
        condition: service_healthy
    volumes:
      - ./certs:/etc/letsencrypt
      - ./webroot:/webroot
      - ./certbot-logs:/var/log/letsencrypt
    entrypoint: >
      /bin/sh -c '
      if [ ! -d "/etc/letsencrypt/live/langkilde.se" ]; then
        certbot certonly --webroot --webroot-path=/webroot -d langkilde.se -d www.langkilde.se -d daniel.langkilde.se -d www.daniel.langkilde.se;
      fi;
      while :; do
        certbot renew --quiet;
        sleep 12h;
      done'
    networks:
      - shared_network

networks:
  shared_network:
    external: true