services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      nginx:
        condition: service_healthy
    volumes:
      - ./certs:/etc/letsencrypt                    # Directory to store certificates
      - ./webroot:/webroot                          # Directory for ACME challenges
      - ./certbot-logs:/var/log/letsencrypt         # Directory for Certbot logs
    entrypoint: >
      /bin/sh -c '
      if [ ! -d "/etc/letsencrypt/live/langkilde.se" ]; then
        certbot certonly --webroot --webroot-path=/webroot -d langkilde.se -d www.langkilde.se -d daniel.langkilde.se -d www.daniel.langkilde.se;
      fi;
      while :; do
        certbot renew --quiet --deploy-hook "nginx -s reload";
        sleep 12h;
      done'
    networks:
      - shared_network

  nginx:
    image: nginx:latest
    container_name: nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro       # Nginx configuration
      - ./certs:/etc/letsencrypt                    # SSL certificates (including self-signed)
      - ./nginx-logs:/var/log/nginx                 # Log directory
      - ./webroot:/webroot                          # Webroot for ACME challenges
    networks:
      - shared_network

networks:
  shared_network:
    external: true